### ISSUE TITLE
Path for grot folders as an atribute

### ISSUE THREAD

**Issue by tymurbaniak** [tymurbaniak/grotserv#9]
It would be handy and much easier to setup anything with grot if it could take path to project and results folder as a command line atribute..

**Comment by tutajrobert** [comment]
Added in last commit. If no parameters added after python run.py GRoT will be run normally.

One can put his own path to image file and results folder in the following ways. Warning: os.separators should be properly inputted. GRoT will not check paths.
*** Input image is in C:\im.bmp
python run.py -proj C:\im.bmp
*** Results folder should be C:\results
python run.py -res C:\results
or python run.py -res C:\results\
*** Input image is C:\im.bmp and results folder C:\results
python -proj C:\im.bmp -res C:\results
or python -res C:\results -proj C:\im.bmp
